In [4]:
import ast 
import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.multiclass import OneVsOneClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix

In [5]:
%ls 

 data_fit.ipynb*        'online shoppers'/   train.csv*
 data_inspector.ipynb*   test.csv*


In [6]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()

Administrative_Duration  Informational  Informational_Duration  \
0                      0.0            7.0                     1.0   
1                      0.0            0.0                     0.0   
2                      0.0            0.0                     0.0   
3                      0.0            2.0                     1.0   
4                      0.0            0.0                     0.0   

   ProductRelated  ProductRelated_Duration  BounceRates  ExitRates  \
0              60                      3.0     0.008759   0.028382   
1              94                      7.0     0.008844   0.023562   
2              20                      0.0     0.000000   0.022222   
3               8                      0.0     0.018182   0.033333   
4               6                      0.0     0.066667   0.083333   

   PageValues  SpecialDay  Month  OperatingSystems  Browser  Region  \
0         0.0         0.0      7                 3        2       1   
1         0.0         0.0      7                 2        2       1   
2         0.0         0.0      6                 2       10       3   
3         5.0         0.0      7                 1        1       2   
4         0.0         0.2      6                 2        2       2   

   TrafficType  VisitorType  Weekend  Revenue  
0            3            2    False    False  
1            2            2    False     True  
2            3            2    False    False  
3            7            2    False    False  
4            2            2    False    False

In [7]:

x_test = test.iloc[:,:-2].to_numpy()
y_test = test.iloc[:,-1].to_numpy()

x = train.iloc[:,:-2].to_numpy()
y = train.iloc[:,-1].to_numpy()

# Multi-layer Perceptron Classifier

In [10]:
clf = MLPClassifier()
clf.fit(x, y)
y_pred = clf.predict(x_test)
print('accuracy_score:   \t', accuracy_score(y_pred, y_test),
      '\nprecision_score:\t', precision_score(y_pred, y_test),
      '\nrecall_score:   \t', recall_score(y_pred, y_test),
      '\nf1_score:       \t', f1_score(y_pred, y_test))
print('confusion_matrix:\n',confusion_matrix(y_pred, y_test))

accuracy_score:   	 0.8736790366183338 
precision_score:	 0.6549520766773163 
recall_score:   	 0.5790960451977402 
f1_score:       	 0.6146926536731635
confusion_matrix:
 [[3145  216]
 [ 298  410]]


/media/amir/Third/Applied_Machine_Learning_S20_Assignments/aml_env/lib/python3.6/site-packages/sklearn/neural_network/_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# Support Vector Machine

In [11]:
clf = SVC(kernel='rbf')
clf.fit(x, y)
y_pred = clf.predict(x_test)
print('accuracy_score:   \t', accuracy_score(y_pred, y_test),
      '\nprecision_score:\t', precision_score(y_pred, y_test),
      '\nrecall_score:   \t', recall_score(y_pred, y_test),
      '\nf1_score:       \t', f1_score(y_pred, y_test))
print('confusion_matrix:\n',confusion_matrix(y_pred, y_test))

accuracy_score:   	 0.8876873924797247 
precision_score:	 0.426517571884984 
recall_score:   	 0.7315068493150685 
f1_score:       	 0.5388496468213925
confusion_matrix:
 [[3345  359]
 [  98  267]]


# Gaussian Naive Bayes

In [12]:
clf = GaussianNB()
clf.fit(x, y)
y_pred = clf.predict(x_test)
print('accuracy_score:   \t', accuracy_score(y_pred, y_test),
      '\nprecision_score:\t', precision_score(y_pred, y_test),
      '\nrecall_score:   \t', recall_score(y_pred, y_test),
      '\nf1_score:       \t', f1_score(y_pred, y_test))
print('confusion_matrix:\n',confusion_matrix(y_pred, y_test))

accuracy_score:   	 0.7645613172769722 
precision_score:	 0.7987220447284346 
recall_score:   	 0.37537537537537535 
f1_score:       	 0.5107252298263534
confusion_matrix:
 [[2611  126]
 [ 832  500]]


# Bernoulli Naive Bayes

In [13]:
clf = BernoulliNB()
clf.fit(x, y)
y_pred = clf.predict(x_test)
print('accuracy_score:   \t', accuracy_score(y_pred, y_test),
      '\nprecision_score:\t', precision_score(y_pred, y_test),
      '\nrecall_score:   \t', recall_score(y_pred, y_test),
      '\nf1_score:       \t', f1_score(y_pred, y_test))
print('confusion_matrix:\n',confusion_matrix(y_pred, y_test))

accuracy_score:   	 0.856475792578029 
precision_score:	 0.5638977635782748 
recall_score:   	 0.5316265060240963 
f1_score:       	 0.5472868217054263
confusion_matrix:
 [[3132  273]
 [ 311  353]]
